name: Build Linux wheels
on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libclang-dev
        
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Build wheel
      run: |
        pip install maturin
        maturin build --release
        
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: linux-wheel
        path: target/wheels/*.whl
